### ISSUE TITLE
ISO 8601 timestamps with milliseconds are not parsed properly

### ISSUE THREAD

**Issue by aaronzen** [mission-liao/pyswagger#83]
When timestamp strings include milliseconds, the millisecond portion and (more importantly) the timezone information is not correctly parsed.

For example:
```
>>> from pyswagger import utils
>>> utils.from_iso8601("2016-08-05T03:14:14Z")
datetime.datetime(2016, 8, 5, 3, 14, 14, tzinfo=<pyswagger.utils.FixedTZ object at 0x10e0316d0>)
>>> utils.from_iso8601("2016-08-05T03:14:14.809Z")
datetime.datetime(2016, 8, 5, 3, 14, 14)
```

Note in the second example, timezone information is missing.  

Compare this to dateutil:
```
>>> dateutil.parser.parse("2016-08-05T03:14:14.809Z")
datetime.datetime(2016, 8, 5, 3, 14, 14, 809000, tzinfo=tzutc())
```

In my use case, this is causing problems interoperating with a swagger server that gives millisecond timestamps.

**Comment by mission-liao** [comment]
The dot is not handled in the regular-expression used to parse the ISO-8601 strings. Thanks for pointing out, I'll add them this weekend.

**Comment by aaronzen** [comment]
Thank you! I really appreciate the quick response.

**Comment by mission-liao** [comment]
This issue should be fixed in latest release. (I forget to include the example string you provided in this issue to test, it would be included in next commit)

BTW, the original reasons to write the part to parse ISO 8601 formatted string instead of using [Arrow](https://github.com/crsmithdev/arrow):
 - I want to minimize the dependency of this project
 - I think it shouldn't be hard

Now I need to reconsider the second reason :(
