### ISSUE TITLE
How to instantiate App from a json string? 

### ISSUE THREAD

**Issue by skasturi** [mission-liao/pyswagger#86]
I am storing the JSON in a database and would like to access it from there. Is there a way to create App from a string?

**Comment by mission-liao** [comment]
It was provided before Swagger 1.2, but removed after 2.0. I could add it back with these concerns in mind:
 - A DictGetter would be added under pyswagger.getter
 - You would need to use it in this way (instead of using SwaggerApp.create)
```python
SwaggerApp.load(....)
SwaggerApp.prepare(...)
```
 - it would be better (or essential, not sure before I really try it) to provide a url because it is required in some scenario. ex. it would be used as host when no 'host' property in Swagger Object.

I'll try this part this weekend. before that, the only way for you is save it to a temporarily file and load it back (looks really dumb)

**Comment by skasturi** [comment]
Thanks. I will give it a shot once you add it.

**Comment by mission-liao** [comment]
I just implement this part, please refer to [this document](https://github.com/mission-liao/pyswagger/blob/master/docs/md/ref/resolver.md) for its usage. There is some limitation for multiple documents case, but should be fine for single document. Feedback is welcome.
